# Generated by Django 6.0.5 on 2026-05-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(default='0:00', max_length=10, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
