# Generated by Django 6.0.5 on 2026-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_options_remove_album_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='Текст песни'),
        ),
    ]
