# Generated by Django 6.0.5 on 2026-05-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='lyrics',
        ),
    ]
