# Generated by Django 6.0.5 on 2026-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_track_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
