# Generated by Django 6.0.5 on 2026-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
