# Generated by Django 6.0.5 on 2026-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
