# Generated by Django 6.0.5 on 2026-05-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='added_at',
        ),
    ]
