# Generated by Django 6.0.5 on 2026-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_album_options_remove_userlibrary_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='info',
        ),
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
    ]
