# Generated by Django 6.0.5 on 2026-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_album_cover_url_remove_album_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
