# Generated by Django 6.0.5 on 2026-05-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_album_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='url',
        ),
    ]
